import ThreeCanvas from "@/threejs/canvas";
import "../styles/global.scss";
import type { Metadata } from "next";
import WrapperView from "@/components/wrapperView";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <WrapperView>{children}</WrapperView>
        <ThreeCanvas />
      </body>
    </html>
  );
}
